export enum Type {
  Normal = "Normal",
  Fighting = "Fighting",
  Flying = "Flying",
  Poison = "Poison",
  Ground = "Ground",
  Rock = "Rock",
  Bug = "Bug",
  Ghost = "Ghost",
  Steel = "Steel",
  Fire = "Fire",
  Grass = "Grass",
  Water = "Water",
  Electric = "Electric",
  Psychic = "Psychic",
  Ice = "Ice",
  Dragon = "Dragon",
  Dark = "Dark",
  Fairy = "Fairy",
}
